name = "TimeSync"
uuid = "326ec072-e1cf-4fd0-9771-25048c9d02d8"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
